#%RAML 0.8
---
#===============================================================
#  Products API - RAML sample project
#  References:
#    - RAML Specification - http://raml.org/spec.html
#    
#===============================================================
title: Products API
version: v0.1
baseUri: http://localhost:8081


#List of media type to support
mediaType:  application/json
#List of protocols to support for baseUri
protocols: [ HTTP, HTTPS ]

#===============================================================
#  API documentation
#===============================================================
documentation:
 - title: Welcome Page
   content: |
     Hi, this is a sample *open source project* to demonstrate the implementation of **RAML**  specification with Anypoint Studio.
     
     This project demonstrate an imaginary bookstore as a sample demo and demonstrate an API for an imaginary book store for their shippment.
     
     For more info, please visit [My Git repo](https://github.com/anirban37?tab=repositories)
     
 - title: About test
   content: A **sample** project to *demonstrate* implementation of RAML
     specification with Anypoint Studio and demonstrate an API for an imaginary bookstore.
     
     Build with API Designer                        


  #---------------------------------------------------------------
  # Resource section.
  #---------------------------------------------------------------
/myBook/{bookId}/getStatus: 
  get: 
    description: returns the book status for the specific bookId
    responses: 
      200: 
        description: Retrieve book status for the specific bookId.
        body: 
          application/json: 
            example: |
              {
                "BookDetails": [
                  {
                    "Description": "New series",
                    "BookName": "My Book",
                    "Author": "Anirban"
                  }
                ],
                "Price": 200,
                "BookId": "AASS56FFF",
                "Status": "Sold",
                "ConsigneeAddress2": "A",
                "ConsigneeCity": "Bangalore",
                "ConsigneeName": "MultiStarrer",
                "ConsigneeNumber": "123",
                "ConsigneeState": "IND",
                "ConsigneeZip": "34689",
                "DeliveryDate": "2015-11-02",
                "DeliveryTime": "1317",
                "Pieces": "1",
                "ProNumber": "000000000",
                "ShipperAddress1": "A",
                "ShipperAddress2": "A",
                "ShipperNumber": "123",
                "ShipperName": "STRIKER Imaginary shipper",
                "Quantity": 1,
                "Genre": "Comedy",
                "DestinationTerminalPhoneNumber": "535355535"
              }             
/myBook/getAllStatus: 
  get: 
    description: returns the all book status
    responses: 
      200: 
        description: Retrieve all book status.
        body: 
          application/json: 
            example: |
             {
                "BookDetails": [
                  {
                    "Description": "New series",
                    "BookName": "My Book",
                    "Author": "Anirban"
                  },
                  {
                    "Description": "New series books",
                    "BookName": "The Truth",
                    "Author": "John Smith"
                  },
                  {
                    "Description": "New series books",
                    "BookName": "Smilling away",
                    "Author": "Wendy Carlos"
                  }
                ],
                "Price": 200,
                "BookId": "AASS56FFF",
                "Status": "Sold",
                "ConsigneeAddress2": "A",
                "ConsigneeCity": "Bangalore",
                "ConsigneeName": "MultiStarrer",
                "ConsigneeNumber": "123",
                "ConsigneeState": "IND",
                "ConsigneeZip": "34689",
                "DeliveryDate": "2015-11-02",
                "DeliveryTime": "1317",
                "Pieces": "1",
                "ProNumber": "000000000",
                "ShipperAddress1": "A",
                "ShipperAddress2": "A",
                "ShipperNumber": "123",
                "ShipperName": "STRIKER Imaginary shipper",
                "Quantity": 1,
                "Genre": "Comedy",
                "DestinationTerminalPhoneNumber": "535355535"
              }             
