#%RAML 0.8
---
#===============================================================
#  Products API - RAML sample project
#  References:
#    - RAML Specification - http://raml.org/spec.html
#    
#===============================================================
title: Products API
version: v0.1
baseUri: http://localhost:8081


#List of media type to support
mediaType:  application/json
#List of protocols to support for baseUri
protocols: [ HTTP, HTTPS ]

#===============================================================
#  API documentation
#===============================================================
documentation:
 - title: Welcome Page
   content: |
     Hi, this is a sample *open source project* to demonstrate the implementation of **RAML**  specification with Anypoint Studio.
     
     This project demonstrate an imaginary shipping project as a sample demo and demonstrate an API for an imaginary shipping company for their shippment.
     
     For more info, please visit [My Git repo](https://github.com/anirban37?tab=repositories)
     
 - title: About test
   content: A **sample** project to *demonstrate* implementation of RAML
     specification with Anypoint Studio and demonstrate an API for an imaginary shipping company.
     
     Build with API Designer                        


  #---------------------------------------------------------------
  # Resource section.
  #---------------------------------------------------------------
/myshipper/shipment/{proNum}/getstatus: 
  get: 
    description: returns the carrier status for the specific tracking for striker imaginary shipper
    responses: 
      200: 
        description: Retrieve carrier status from striker imaginary shipper.
        body: 
          application/json: 
            example: |
              {
                "TrackingLine": [
                  {
                    "Description": "Shipment Picked Up From Shipper In New Delhi, IND",
                    "Date": "2015-10-30",
                    "Time": "15:12:00"
                  },
                  
                  {
                    "Description": "Shipment In Transit.",
                    "Date": "2015-10-30",
                    "Time": "21:35:00"
                  },
                  {
                    "Description": "Shipment Arrived At Destination Terminal In Mumbai, IND",
                    "Date": "2015-10-31",
                    "Time": "06:17:00"
                  },
                  {
                    "Description": "Shipment Out For Delivery To Consignee In MultiStarrer,Bangalore, IND",
                    "Date": "2015-11-02",
                    "Time": "08:40:00"
                  },
                  {
                    "Description": "Delivered To Consignee In MultiStarrer,Bangalore, IND",
                    "Date": "2015-11-02",
                    "Time": "13:27:00"
                  }
                ],
                "AmountDue": "13300",
                "ConsigneeAddress1": "ABC road , Bangalore",
                "Status": "Done",
                "ConsigneeAddress2": "A",
                "ConsigneeCity": "Bangalore",
                "ConsigneeName": "MultiStarrer",
                "ConsigneeNumber": "123",
                "ConsigneeState": "IND",
                "ConsigneeZip": "34689",
                "DeliveryDate": "2015-11-02",
                "DeliveryTime": "1317",
                "Pieces": "1",
                "ProNumber": "000000000",
                "ShipperAddress1": "A",
                "ShipperAddress2": "A",
                "ShipperNumber": "123",
                "ShipperName": "STRIKER Imaginary shipper",
                "Weight": "220",
                "OriginTerminalPhoneNumber": "1235",
                "DestinationTerminalPhoneNumber": "535355535"
              }             
/striker/shipment/{proNum}/getstatus: 
  get: 
    description: returns the carrier status for the specific tracking for striker imaginary shipper
    responses: 
      200: 
        description: Retrieve carrier status.
        body: 
          application/json: 
            example: |
              {
                "TrackingLine": [
                  {
                    "Description": "Shipment Picked Up From Shipper In New Delhi, IND",
                    "Date": "2015-10-30",
                    "Time": "15:12:00"
                  },
                  
                  {
                    "Description": "Shipment In Transit.",
                    "Date": "2015-10-30",
                    "Time": "21:35:00"
                  },
                  {
                    "Description": "Shipment Arrived At Destination Terminal In Mumbai, IND",
                    "Date": "2015-10-31",
                    "Time": "06:17:00"
                  },
                  {
                    "Description": "Shipment Out For Delivery To Consignee In MultiStarrer,Bangalore, IND",
                    "Date": "2015-11-02",
                    "Time": "08:40:00"
                  },
                  {
                    "Description": "Delivered To Consignee In MultiStarrer,Bangalore, IND",
                    "Date": "2015-11-02",
                    "Time": "13:27:00"
                  }
                ],
                "AmountDue": "13300",
                "ConsigneeAddress1": "ABC road , Bangalore",
                "Status": "Done",
                "ConsigneeAddress2": "A",
                "ConsigneeCity": "Bangalore",
                "ConsigneeName": "MultiStarrer",
                "ConsigneeNumber": "123",
                "ConsigneeState": "IND",
                "ConsigneeZip": "34689",
                "DeliveryDate": "2015-11-02",
                "DeliveryTime": "1317",
                "Pieces": "1",
                "ProNumber": "00000000",
                "ShipperAddress1": "A",
                "ShipperAddress2": "A",
                "ShipperNumber": "123",
                "ShipperName": "STRIKER Imaginary shipper",
                "Weight": "220",
                "OriginTerminalPhoneNumber": "1235",
                "DestinationTerminalPhoneNumber": "535355535"
              }             